/**
 * @file digamma.c
 * @brief Real and complex digamma implementations with fixed, adaptive, and Mortici tails.
 *
 * The implementations use recurrence to shift arguments into an asymptotic
 * region, reflection identities for negative real/complex inputs when enabled,
 * and Bernoulli/Stirling tails for the final approximation. Public variants
 * differ mainly in the number of tail coefficients or the speed/accuracy trade.
 */

#include "internal/polygamma_internal.h"

static inline double digamma_core_f64(double x, int tail_terms);
static inline float  digamma_core_f32(float x, int tail_terms);
static SimComplexDouble digamma_core_c64(SimComplexDouble z, int tail_terms);

static inline double digamma_mid_1_2_f64(double x) {
    /* Generated by tools/approx/oakfield_minimax for digamma on [1, 2].
     * Original coefficients are Chebyshev-basis rational (6, 5); these are
     * transformed to powers of y = x - 1 for Horner evaluation.
     */
    const double y = x - 1.0;

    const double p = FMA(y,
                         FMA(y,
                             FMA(y,
                                 FMA(y,
                                     FMA(y,
                                         FMA(y, 6.5127627380449206e-06,
                                             0.0020639282645390053),
                                         0.042298695568535903),
                                     0.25140297896749503),
                                 0.50637604662505098),
                             0.18120872899074339),
                         -0.21825887618751916);
    const double q = FMA(y,
                         FMA(y,
                             FMA(y,
                                 FMA(y,
                                     FMA(y, 0.00047048130918966998,
                                         0.015253188176546778),
                                     0.14073112542092631),
                                 0.51145573085839002),
                             0.76363085805570574),
                         0.37812361905450348);
    return p / q;
}

static inline double digamma_stirling_f64(double x, int tail_terms) {
    const double inv  = 1.0 / x;
    const double inv2 = inv * inv;
    double       series = 0.0;
    double       inv2n  = inv2;
    int          N      = tail_terms;
    int          maxN   = (int) (sizeof(C2) / sizeof(C2[0]));
    if (N > maxN)
        N = maxN;
    for (int n = 1; n <= N; ++n) {
        series = FMA(C2[n - 1], inv2n, series);
        inv2n *= inv2;
    }
    return log(x) - 0.5 * inv + series;
}

static inline double digamma_large_f64(double x, int tail_terms) {
    if (tail_terms < 7)
        return digamma_stirling_f64(x, tail_terms);

    x -= 1.0;
    const double inv = 1.0 / x;
    const double z   = inv * inv;
    const double p   = FMA(z,
                         FMA(z,
                             FMA(z,
                                 FMA(z,
                                     FMA(z,
                                         FMA(z,
                                             FMA(z, -0.44325980392156863,
                                                 0.083333333333333333),
                                             -0.021092796092796094),
                                         0.0075757575757575758),
                                     -0.0041666666666666666),
                                 0.0039682539682539683),
                             -0.0083333333333333332),
                         0.083333333333333333);
    return log(x) + 0.5 * inv - z * p;
}

/**
 * @brief Evaluate double-precision digamma with a 12-term Stirling tail.
 *
 * @param x Real argument. Nonpositive integer poles return NaN.
 * @return Approximation to psi(x).
 */
double sim_digamma_f64_12(double x) {
    return digamma_core_f64(x, 12);
}

/**
 * @brief Evaluate double-precision digamma with a 7-term Stirling tail.
 *
 * @param x Real argument. Nonpositive integer poles return NaN.
 * @return Approximation to psi(x) using fewer Bernoulli coefficients.
 */
double sim_digamma_f64_7(double x) {
    return digamma_core_f64(x, 7);
}

/**
 * @brief Evaluate double-precision digamma with a 5-term Stirling tail.
 *
 * @param x Real argument. Nonpositive integer poles return NaN.
 * @return Approximation to psi(x) optimized for lower tail cost.
 */
double sim_digamma_f64_5(double x) {
    return digamma_core_f64(x, 5);
}

/**
 * @brief Evaluate float digamma with the default float tail length.
 *
 * @param x Real single-precision argument.
 * @return Approximation to psi(x), rounded to float.
 */
float sim_digamma_f32_12(float x) {
    return digamma_core_f32(x, 8);
}

/**
 * @brief Evaluate float digamma with a 7-term tail.
 *
 * @param x Real single-precision argument.
 * @return Approximation to psi(x), rounded to float.
 */
float sim_digamma_f32_7(float x) {
    return digamma_core_f32(x, 7);
}

/**
 * @brief Evaluate float digamma with a 5-term tail.
 *
 * @param x Real single-precision argument.
 * @return Approximation to psi(x), rounded to float.
 */
float sim_digamma_f32_5(float x) {
    return digamma_core_f32(x, 5);
}

/**
 * @brief Evaluate double-precision digamma using a Mortici-style fast approximation.
 *
 * This backend shifts positive inputs to at least 3, evaluates a compact
 * logarithmic/rational approximation, then unwinds the recurrence. It is
 * intended for throughput-sensitive paths where last-bit accuracy is secondary.
 *
 * @param x Real argument. Nonpositive integer poles return NaN.
 * @return Fast approximation to psi(x).
 */
double sim_digamma_f64_mortici(double x) {
    if (!isfinite(x))
        return NAN;
    if (x <= 0.0) {
        if (sim_is_int(x))
            return NAN;
        return sim_digamma_f64_mortici(1.0 - x) - M_PI * sim_cotpi(x);
    }

    int nshift = 0;
    while (x < 3.0) {
        x += 1.0;
        nshift++;
    }

    double inv   = 1.0 / x;
    double inv2  = inv * inv;
    double inv3  = inv2 * inv;
    double delta = 0.5 + (1.0 / 24.0) * inv - (1.0 / 48.0) * inv2 + (23.0 / 5760.0) * inv3;
    double y     = log(x + delta) - 0.5 * inv;
    while (nshift--)
        y -= 1.0 / (--x);
    return y;
}

/**
 * @brief Evaluate float digamma using a Mortici-style fast approximation.
 *
 * @param x Real single-precision argument. Nonpositive integer poles return NaN.
 * @return Fast approximation to psi(x), rounded to float.
 */
float sim_digamma_f32_mortici(float x) {
    if (!isfinite(x))
        return NAN;
    if (x <= 0.0f) {
        if (sim_is_intf(x))
            return NAN;
        return sim_digamma_f32_mortici(1.0f - x) - (float) M_PI * sim_cotpi_f(x);
    }

    int nshift = 0;
    while (x < 3.0f) {
        x += 1.0f;
        nshift++;
    }

    float inv   = 1.0f / x;
    float inv2  = inv * inv;
    float inv3  = inv2 * inv;
    float delta = 0.5f + (1.0f / 24.0f) * inv - (1.0f / 48.0f) * inv2 + (23.0f / 5760.0f) * inv3;
    float y     = logf(x + delta) - 0.5f * inv;
    while (nshift--)
        y -= 1.0f / (--x);
    return y;
}

/**
 * @brief Evaluate double-precision digamma with an adaptive Bernoulli tail.
 *
 * The tail is extended until a geometric-style bound on the next Bernoulli term
 * drops below `tol`, up to the implementation's hard loop bound.
 *
 * @param x Real argument. Nonpositive integer poles return NaN.
 * @param tol Absolute stopping tolerance for the asymptotic tail.
 * @return Approximation to psi(x), or NaN for invalid inputs/poles.
 */
double sim_digamma_f64_tail(double x, double tol) {
    if (!isfinite(x))
        return NAN;
    if (x <= 0.0) {
        if (sim_is_int(x))
            return NAN;
#if defined(SIM_TRIG_FREE)
        double z     = x;
        double shift = 0.0;
        int    iter  = 0;
        while (z <= 0.0) {
            shift -= 1.0 / z;
            z += 1.0;
            if (z <= 0.0 && sim_is_int(z))
                return NAN;
            if (++iter >= 1024)
                return NAN;
        }
        return shift + sim_digamma_f64_tail(z, tol);
#else
        double nearest = nearbyint(x);
        double dist    = fabs(x - nearest);
        if (dist < DBL_EPSILON)
            return NAN;
#if SIM_DIAGNOSTICS
        sim_special_diag_track_reflection();
        sim_special_diag_track_pole_distance(dist);
#endif
        return sim_digamma_f64_tail(1.0 - x, tol) - M_PI * sim_cotpi(x);
#endif
    }

    double y           = 0.0;
    double z           = x;
    double shift_accum = 0.0;
    while (z + 2.0 < SIM_STIRLING_SHIFT_THRESHOLD) {
        y -= 1.0 / z;
        shift_accum += 1.0;
        z += 1.0;
        y -= 1.0 / z;
        shift_accum += 1.0;
        z += 1.0;
    }
    while (z < SIM_STIRLING_SHIFT_THRESHOLD) {
        y -= 1.0 / z;
        shift_accum += 1.0;
        z += 1.0;
    }
#if SIM_DIAGNOSTICS
    if (shift_accum > 0.0)
        sim_special_diag_track_recurrence(shift_accum);
#endif

    const double inv  = 1.0 / z;
    const double inv2 = inv * inv;
    double       tail  = 0.0;
    double       inv2n = inv2;
    for (int n = 1; n < 100; ++n) {
        double term = -B2[n - 1] * inv2n / (2.0 * n);
        tail += term;
        double bound = fabs(term * inv2 / (1.0 - inv2));
        if (bound < tol)
            break;
        inv2n *= inv2;
    }
    y += log(z) - 0.5 * inv + tail;
#if SIM_DIAGNOSTICS
    sim_special_diag_track_stirling_tail(tail);
#endif
    return y;
}

/**
 * @brief Core real digamma evaluator with reflection, recurrence, and fixed tail terms.
 *
 * @param x Real argument.
 * @param tail_terms Requested number of Bernoulli-pair coefficients.
 * @return Approximation to psi(x), or NaN for poles/invalid inputs.
 */
static inline double digamma_core_f64(double x, int tail_terms) {
    if (!isfinite(x))
        return NAN;

    double acc = 0.0;
    double z   = x;
#if !defined(SIM_TRIG_FREE)
    if (z <= 0.0) {
        if (sim_is_int(z))
            return NAN;
        double nearest = nearbyint(z);
        double dist    = fabs(z - nearest);
        if (dist < DBL_EPSILON)
            return NAN;
        return digamma_core_f64(1.0 - z, tail_terms) - M_PI * sim_cotpi(z);
    }
#else
    int iter = 0;
    while (z <= 0.0) {
        if (sim_is_int(z))
            return NAN;
        acc -= 1.0 / z;
        z += 1.0;
        if (z <= 0.0 && sim_is_int(z))
            return NAN;
        if (++iter >= 1024)
            return NAN;
    }
#endif

    const double large_threshold = tail_terms >= 7 ? 8.0 : SIM_STIRLING_SHIFT_THRESHOLD;
    if (z >= large_threshold)
        return acc + digamma_large_f64(z, tail_terms);

    while (z > 2.0) {
        z -= 1.0;
        acc += 1.0 / z;
    }

    if (z < 1.0) {
        acc -= 1.0 / z;
        z += 1.0;
    }
    return acc + digamma_mid_1_2_f64(z);
}

/**
 * @brief Core float digamma evaluator with reflection, recurrence, and fixed tail terms.
 *
 * @param x Real single-precision argument.
 * @param tail_terms Requested number of float Bernoulli-pair coefficients.
 * @return Approximation to psi(x), or NaN for poles/invalid inputs.
 */
static inline float digamma_core_f32(float x, int tail_terms) {
    if (!isfinite(x))
        return NAN;

    float acc = 0.0f;
    float z   = x;
#if !defined(SIM_TRIG_FREE)
    if (z <= 0.0f) {
        if (sim_is_intf(z))
            return NAN;
        float nearest = nearbyintf(z);
        float dist    = fabsf(z - nearest);
        if (dist < FLT_EPSILON)
            return NAN;
        return digamma_core_f32(1.0f - z, tail_terms) - (float) M_PI * sim_cotpi_f(z);
    }
#else
    int iter = 0;
    while (z <= 0.0f) {
        if (sim_is_intf(z))
            return NAN;
        acc -= 1.0f / z;
        z += 1.0f;
        if (z <= 0.0f && sim_is_intf(z))
            return NAN;
        if (++iter >= 1024)
            return NAN;
    }
#endif

    while (z + 2.0f < (float) SIM_STIRLING_SHIFT_THRESHOLD) {
        acc -= 1.0f / z;
        z += 1.0f;
        acc -= 1.0f / z;
        z += 1.0f;
    }
    while (z < (float) SIM_STIRLING_SHIFT_THRESHOLD) {
        acc -= 1.0f / z;
        z += 1.0f;
    }

    float inv    = 1.0f / z;
    float inv2   = inv * inv;
    float series = 0.0f;
    float inv2n  = inv2;
    int   N      = tail_terms;
    int   maxN   = (int) (sizeof(C2f) / sizeof(C2f[0]));
    if (N > maxN)
        N = maxN;
    for (int n = 1; n <= N; ++n) {
        series = FMA(C2f[n - 1], inv2n, series);
        inv2n *= inv2;
    }
    return acc + logf(z) - 0.5f * inv + series;
}

/**
 * @brief Evaluate complex digamma using a Mortici-style fast approximation.
 *
 * Complex inputs with negative real part are reflected with
 * `psi(z) = psi(1-z) - pi*cot(pi*z)`. Positive inputs are shifted before the
 * same compact Mortici-style approximation used by the real path.
 *
 * @param z Complex argument.
 * @return Fast complex approximation to psi(z), or `{NAN, NAN}` for invalid inputs.
 */
SimComplexDouble sim_digamma_c64_mortici(SimComplexDouble z) {
    if (!isfinite(z.re) || !isfinite(z.im))
        return (SimComplexDouble) { NAN, NAN };
    if (fabs(z.im) < DBL_EPSILON && z.re <= 0.0 && sim_is_int(z.re))
        return (SimComplexDouble) { NAN, NAN };

    double complex w = z.re + I * z.im;
    if (creal(w) <= 0.0) {
        SimComplexDouble one_minus = { 1.0 - z.re, -z.im };
        SimComplexDouble reflected = sim_digamma_c64_mortici(one_minus);
        double complex   s;
        double complex   c;
        sim_sincospi_complex(z.re, z.im, &s, &c);
        double complex out = (reflected.re + I * reflected.im) - M_PI * (c / s);
        return (SimComplexDouble) { creal(out), cimag(out) };
    }

    double complex acc     = 0.0 + 0.0 * I;
    double complex w_shift = w;
    int            nshift  = 0;
    while (creal(w_shift) < 3.0 && nshift < 1024) {
        acc -= 1.0 / w_shift;
        w_shift += 1.0;
        nshift++;
    }

    double complex inv    = 1.0 / w_shift;
    double complex inv2   = inv * inv;
    double complex inv3   = inv2 * inv;
    double complex delta  = 0.5 + (1.0 / 24.0) * inv - (1.0 / 48.0) * inv2 + (23.0 / 5760.0) * inv3;
    double complex approx = clog(w_shift + delta) - 0.5 * inv;
    double complex out    = acc + approx;
    return (SimComplexDouble) { creal(out), cimag(out) };
}

/**
 * @brief Core complex digamma evaluator with reflection and fixed tail terms.
 *
 * @param z Complex argument.
 * @param tail_terms Requested number of Bernoulli-pair coefficients.
 * @return Complex approximation to psi(z), or `{NAN, NAN}` for invalid inputs.
 */
static SimComplexDouble digamma_core_c64(SimComplexDouble z, int tail_terms) {
    double complex cz = z.re + I * z.im;

    if (!isfinite(z.re) || !isfinite(z.im))
        return (SimComplexDouble) { NAN, NAN };

    if (creal(cz) < 0.5) {
#if SIM_DIAGNOSTICS
        sim_special_diag_track_reflection();
#endif
        SimComplexDouble one_minus = { 1.0 - z.re, -z.im };
        SimComplexDouble psi_ref   = digamma_core_c64(one_minus, tail_terms);

        double complex s;
        double complex c;
        sim_sincospi_complex(z.re, z.im, &s, &c);
        double complex out = (psi_ref.re + I * psi_ref.im) - M_PI * (c / s);
        return (SimComplexDouble) { creal(out), cimag(out) };
    }

    double complex acc         = 0.0 + 0.0 * I;
    double complex w           = cz;
    double         shift_accum = 0.0;
    while (creal(w) < SIM_STIRLING_SHIFT_THRESHOLD && cabs(w) < 64.0) {
        acc += -1.0 / w;
        w += 1.0;
        shift_accum += 1.0;
    }

    double complex inv  = 1.0 / w;
    double complex inv2 = inv * inv;
    double complex series = 0.0 + 0.0 * I;
    double complex inv2n  = inv2;
    int            N      = tail_terms;
    int            maxN   = (int) (sizeof(B2) / sizeof(B2[0]));
    if (N > maxN)
        N = maxN;
    for (int n = 1; n <= N; ++n) {
        series += -B2[n - 1] * inv2n / (2.0 * n);
        inv2n *= inv2;
    }

    double complex out = acc + clog(w) - 0.5 * inv + series;
#if SIM_DIAGNOSTICS
    if (shift_accum > 0.0)
        sim_special_diag_track_recurrence(shift_accum);
    sim_special_diag_track_stirling_tail(creal(series));
#else
    (void) shift_accum;
#endif
    return (SimComplexDouble) { creal(out), cimag(out) };
}

/**
 * @brief Evaluate complex double digamma with a 12-term Stirling tail.
 *
 * @param z Complex argument.
 * @return Complex approximation to psi(z).
 */
SimComplexDouble sim_digamma_c64_12(SimComplexDouble z) {
    return digamma_core_c64(z, 12);
}

/**
 * @brief Evaluate complex double digamma with a 7-term Stirling tail.
 *
 * @param z Complex argument.
 * @return Complex approximation to psi(z).
 */
SimComplexDouble sim_digamma_c64_7(SimComplexDouble z) {
    return digamma_core_c64(z, 7);
}

/**
 * @brief Evaluate complex double digamma with a 5-term Stirling tail.
 *
 * @param z Complex argument.
 * @return Complex approximation to psi(z).
 */
SimComplexDouble sim_digamma_c64_5(SimComplexDouble z) {
    return digamma_core_c64(z, 5);
}

/**
 * @brief Evaluate complex float digamma using the Mortici-style approximation.
 *
 * @param zf Complex single-precision argument.
 * @return Complex approximation to psi(zf), rounded to float components.
 */
SimComplexFloat sim_digamma_c32_mortici(SimComplexFloat zf) {
    SimComplexDouble zd = { (double) zf.re, (double) zf.im };
    return sim_complex_to_c32(sim_digamma_c64_mortici(zd));
}

/**
 * @brief Evaluate complex float digamma with a 12-term double backend.
 *
 * @param zf Complex single-precision argument.
 * @return Complex approximation to psi(zf), rounded to float components.
 */
SimComplexFloat sim_digamma_c32_12(SimComplexFloat zf) {
    SimComplexDouble zd = { (double) zf.re, (double) zf.im };
    return sim_complex_to_c32(sim_digamma_c64_12(zd));
}

/**
 * @brief Evaluate complex float digamma with a 7-term double backend.
 *
 * @param zf Complex single-precision argument.
 * @return Complex approximation to psi(zf), rounded to float components.
 */
SimComplexFloat sim_digamma_c32_7(SimComplexFloat zf) {
    SimComplexDouble zd = { (double) zf.re, (double) zf.im };
    return sim_complex_to_c32(digamma_core_c64(zd, 7));
}

/**
 * @brief Evaluate complex float digamma with a 5-term double backend.
 *
 * @param zf Complex single-precision argument.
 * @return Complex approximation to psi(zf), rounded to float components.
 */
SimComplexFloat sim_digamma_c32_5(SimComplexFloat zf) {
    SimComplexDouble zd = { (double) zf.re, (double) zf.im };
    return sim_complex_to_c32(digamma_core_c64(zd, 5));
}

/**
 * @brief Evaluate complex double digamma by increasing tail length until convergence.
 *
 * The routine compares successive fixed-tail evaluations and stops when the
 * component-wise change is below `tol`, or after the configured maximum tail
 * sweep.
 *
 * @param z Complex argument.
 * @param tol Absolute convergence threshold on successive approximations.
 * @return Best complex approximation found by the tail sweep.
 */
SimComplexDouble sim_digamma_c64_tail(SimComplexDouble z, double tol) {
    int              N    = 3;
    SimComplexDouble last = digamma_core_c64(z, N);
    for (; N < 60; ++N) {
        SimComplexDouble cur = digamma_core_c64(z, N);
        if (fabs(cur.re - last.re) + fabs(cur.im - last.im) < tol)
            return cur;
        last = cur;
    }
    return last;
}
